In [1]:
import numpy as np

np.random.random((2, 4))

array([[0.40092888, 0.27186434, 0.18021394, 0.30857629],
       [0.18266818, 0.10084392, 0.10529133, 0.99746848]])

In [5]:
T_ = np.arange(10).reshape(2, 5)
T_.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [7]:
ar = np.arange(12).reshape(3, 4)
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
ar[0:, 1:]
ar[1:2, 1:2]

array([[5]])

In [17]:
ar = np.array([10, 8, 15, 7, 19])
ar
print(type(ar))
print(len(ar))
print(np.ndim(ar))
print(np.shape(ar))
print(np.size(ar))

<class 'numpy.ndarray'>
5
1
(5,)
5


In [20]:
a1 = np.arange(10, 100, 10).reshape(3,3)
a1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [23]:
a2 = np.arange(10,25).reshape(3,5)
a3 = np.arange(11, 36).reshape(5,5)
a2
a3

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [26]:
a4 = np.arange(74, 250, 5).reshape(3, 3, 4)
a4

array([[[ 74,  79,  84,  89],
        [ 94,  99, 104, 109],
        [114, 119, 124, 129]],

       [[134, 139, 144, 149],
        [154, 159, 164, 169],
        [174, 179, 184, 189]],

       [[194, 199, 204, 209],
        [214, 219, 224, 229],
        [234, 239, 244, 249]]])

In [32]:
np.ones((2, 5 ,4))


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [34]:
np.zeros((3, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [36]:
np.random.random((5,5,2))

array([[[0.73438341, 0.36353904],
        [0.16370897, 0.32759324],
        [0.34190921, 0.41965629],
        [0.95172713, 0.08058194],
        [0.46483352, 0.08997495]],

       [[0.19398853, 0.30846874],
        [0.53465976, 0.62550679],
        [0.05657732, 0.22711302],
        [0.86532241, 0.5721208 ],
        [0.43537815, 0.6426028 ]],

       [[0.61100406, 0.3089943 ],
        [0.40893719, 0.66412452],
        [0.01241727, 0.62979022],
        [0.57115641, 0.75429995],
        [0.60060161, 0.57878704]],

       [[0.3003406 , 0.35471685],
        [0.18865284, 0.38624103],
        [0.13080679, 0.16652425],
        [0.44214505, 0.30973394],
        [0.11621679, 0.38813811]],

       [[0.05643719, 0.17464148],
        [0.97381453, 0.11920276],
        [0.33390604, 0.65408598],
        [0.92154275, 0.67062166],
        [0.2142387 , 0.13520147]]])

In [40]:
np.random.uniform(4.5, 7, (7,1,4))

array([[[5.22165047, 5.02302454, 5.21116057, 6.01665605]],

       [[6.04844488, 5.20850382, 5.47089272, 4.70630023]],

       [[6.48296702, 4.56852507, 6.5932138 , 5.64840385]],

       [[4.72703009, 6.03478723, 6.1302977 , 5.9903195 ]],

       [[6.74093509, 5.50499696, 5.62018253, 5.2555349 ]],

       [[4.66516996, 5.51300676, 5.16788708, 5.29629081]],

       [[6.63620018, 4.98352651, 6.29136369, 5.46796739]]])

In [41]:
np.random.randint(10, 20, (3,3,9))

array([[[16, 11, 18, 10, 19, 10, 11, 11, 17],
        [19, 13, 18, 13, 18, 14, 10, 11, 13],
        [16, 18, 14, 13, 16, 14, 15, 15, 16]],

       [[19, 11, 13, 15, 13, 14, 17, 16, 17],
        [16, 12, 16, 12, 19, 10, 12, 17, 17],
        [17, 17, 17, 17, 17, 15, 19, 18, 11]],

       [[13, 16, 16, 15, 12, 12, 17, 12, 13],
        [16, 11, 17, 10, 10, 11, 18, 19, 13],
        [12, 16, 13, 16, 18, 10, 14, 11, 11]]])

In [42]:
np.linspace(110, 120, 5)

array([110. , 112.5, 115. , 117.5, 120. ])

In [48]:
a6 = np.arange(27).reshape(3,9)
a6.T

array([[ 0,  9, 18],
       [ 1, 10, 19],
       [ 2, 11, 20],
       [ 3, 12, 21],
       [ 4, 13, 22],
       [ 5, 14, 23],
       [ 6, 15, 24],
       [ 7, 16, 25],
       [ 8, 17, 26]])

In [51]:
a7 = np.arange(24).reshape(3,2,4)
a7

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [52]:
a7[1:, 1:, :1]

array([[[12]],

       [[20]]])

In [53]:
a8 = np.array([1,2,3,4,5])
a8*2

array([ 2,  4,  6,  8, 10])

In [54]:
ar0 = np.arange(12).reshape(4, 3)
ar1 = np.arange(3)
ar2 = np.arange(4).reshape(4,1)
print(ar0, '\n', ar1, '\n', ar2)
ar0 + ar1
ar0 + ar2

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 
 [0 1 2] 
 [[0]
 [1]
 [2]
 [3]]


array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [61]:
a9 = np.arange(48).reshape(3,4,4)

np.max(a9)

47

In [62]:
np.min(a9)

0

In [65]:
a10 = np.random.randint(0, 100,(3,4,4))
a10

array([[[35, 18, 18, 86],
        [74, 79, 11, 82],
        [40, 50, 99, 69],
        [72, 17, 32,  2]],

       [[88,  2, 25, 27],
        [ 3, 15, 89,  7],
        [68, 30, 36, 28],
        [18, 49,  7, 88]],

       [[18, 22, 53,  1],
        [16, 85, 21, 69],
        [74, 96, 22, 97],
        [52, 47,  5, 18]]])

In [66]:
np.min(a10)

1

In [67]:
np.max(a10)

99

In [68]:
np.argmax(a10)

10

In [69]:
np.median(a10)

33.5

In [70]:
a11 = np.arange(1,31,2).reshape(3,5)
a11

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [71]:
np.sum(a11, axis=0)

array([33, 39, 45, 51, 57])

In [75]:
a12 = np.random.randint(-10,10,(2,5))
a12

array([[ -8,   5,   2,  -2,   3],
       [  3,  -2,  -8, -10,   3]])

In [76]:
np.unique(a12) # ar의 값들을 정렬(중복제거)하여 1차원으로 반환

array([-10,  -8,  -2,   2,   3,   5])

In [77]:
a13 = np.arange(1, 10).reshape(3,3)
a13

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
Dar = a13
Dar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
Dar[0][2] = 1000
Dar

array([[   1,    2, 1000],
       [   4,    5,    6],
       [   7,    8,    9]])

In [82]:
Dar = a13.copy()
Dar

array([[   1,    2, 1000],
       [   4,    5,    6],
       [   7,    8,    9]])

In [83]:
Dar[0][1] = 5000
Dar

array([[   1, 5000, 1000],
       [   4,    5,    6],
       [   7,    8,    9]])

In [84]:
a13

array([[   1,    2, 1000],
       [   4,    5,    6],
       [   7,    8,    9]])

In [85]:
a14 = np.array([7, 5, 9, 10])
a15 = np.array([4, 10, 6, 2])
a14*3 + a15*3


array([33, 45, 45, 36])

In [94]:
a16 = np.array([[7,5,9,10],[4,10,6,2]])
a17 = np.array([[1,3,4,9,],[14,7,6,4]])
a16

array([[ 7,  5,  9, 10],
       [ 4, 10,  6,  2]])

In [97]:
if np.sum(a16[0] - a16[1]) >0:
  print(True)
else:
  print(False)

True


In [98]:
a16 - a17 > 0

array([[ True,  True,  True,  True],
       [False,  True, False, False]])

In [103]:
a18 = np.arange(1, 13).reshape(3,4)
a18

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [108]:
a19 = np.linspace(1,12,3).reshape(3,1)
a19

array([[ 1. ],
       [ 6.5],
       [12. ]])

In [109]:
a18 + a19

array([[ 2. ,  3. ,  4. ,  5. ],
       [11.5, 12.5, 13.5, 14.5],
       [21. , 22. , 23. , 24. ]])

In [110]:
a20 = np.random.randint(-1, 19, (3,3,4))
a20

array([[[11,  7,  6, 18],
        [ 3, 14, -1, 18],
        [ 6, 12,  6,  5]],

       [[18,  6,  2, 11],
        [14,  1,  2, 17],
        [16, 12,  0, 16]],

       [[ 8, 12, 18, 12],
        [ 0,  6,  6,  9],
        [ 6, 11, 15, 18]]])

In [128]:
np.mean(a20) #평균

9.472222222222221

In [111]:
np.sum(a20)

341

In [112]:
np.median(a20)

10.0

In [129]:
np.sum(a20[1:, :2])

142

In [114]:
np.argmax(a20[1:, :2])

0

In [115]:
np.argmin(a20[1:, :2])

12

In [123]:
D2 =a20.copy()
D2

array([[[11,  7,  6, 18],
        [ 3, 14, -1, 18],
        [ 6, 12,  6,  5]],

       [[18,  6,  2, 11],
        [14,  1,  2, 17],
        [16, 12,  0, 16]],

       [[ 8, 12, 18, 12],
        [ 0,  6,  6,  9],
        [ 6, 11, 15, 18]]])

In [127]:
D2[0][0][3] = 0
D2

array([[[11,  7,  6,  0],
        [ 3, 14, -1, 18],
        [ 6, 12,  6,  5]],

       [[18,  6,  2, 11],
        [14,  1,  2, 17],
        [16, 12,  0, 16]],

       [[ 8, 12, 18, 12],
        [ 0,  6,  6,  9],
        [ 6, 11, 15, 18]]])

In [136]:
a21 = np.arange(1,11)
np.random.shuffle(a21)
a21

array([ 6,  8,  9,  2,  5,  7,  1,  3,  4, 10])

In [137]:
a22 = np.arange(1,31).reshape(3,10)
a22

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [138]:
np.random.shuffle(a22)
a22

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [144]:
ar=np.array([[1., 70., 85., 95., 100., 100.],
          [2., 100., 85., 90., 90., 95.],   
          [3., 95., 95., 80., 75., 75.],          
          [4., 65., 75., 70., 90., 100.],
          [5., 90., 80., 85., 95., 95.],          
          [6., 90., 90., 75., 75., 80.],          
          [7., 60., 90., 80., 40., 45.],          
          [8., 85., 90., 75., 60., 90.],              
          [9., 90., 85., 85., 90., 85.]])

